version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./opt:/usr/src/app # ローカルとコンテナ内の同期    
    ports:
      - "3000:3000"
    stdin_open: true 
