version: '3' #docker-composeのバージョン
services: #起動したいコンテナの種類
  redis-server:
    image: 'redis' #redisイメージでコンテナを起動
  node-app:
    build: . #カレントディレクトリのDockerfileからイメージをビルドしてコンテナを起動
    ports: #ポートマッピング([localhostのポート番号]:[コンテナのポート番号])
      - '4001:8081'